### ISSUE TITLE
Incremental dumps

### ISSUE THREAD

**Issue by fxcp** [Kosat/telegram-messages-dump#10]
It would be nice for telegram-messages-dump to be able to update existing dumps instead of reprocessing everything (what is very useful if you want to "backup" your chat's history).

Something like this can work:
1. Read latest message ID from dump file.
2. Save and append everything after this ID.

Problems:
* What to do with machine-unfriendly exporters?
* `-l` option behavior? Maybe "dump X messages after latest message ID"?

**Comment by fxcp** [comment]
Another way to implement this is to keep latest message ID in separate file (output file + `.lastmsg`?).
This will keep main code exporter-agnostic.

1. Read `.lastmsg` if any.
2. Save every message after ID from lastmsg.
3. _Append_ messages to output file.

Still open problems:
* `-l` option behavior? Current implementation reads newer messages first. Can we just skip them if `-l` is specified?

New problems:
* What to do with begin/end exporter hooks?

**Comment by Kosat** [comment]
I'm working on it.

There will be an additional meta-file named the same way as output file with the extension `.meta` containing a simple json object.
Meta file will contain the **last message id** that was written into an output file and the **exporter** name, **channel name** used to generate it.

Then, having a meta-file at your hands, you will be able to run `telegram-messages-dump ... --out=xyz.txt --continue` and it will update xyz.txt dump with the newest messages. 

If you don't have a .meta file but have an old xyz.txt dump you will still be able to update it like
`telegram-messages-dump ... --out=xyz.txt --continue=1234 --exp=text`
Here 1234 is the last message id that is already present in xyz.txt dump. 

This will be called continuous/incremental mode. In this mode `--limit` setting will be ignored. 

> end exporter hook -> will be removed 
> begin exporter hook -> will get additional parameter telling if the tool is running in continuous mode. 
If so, exporter is expected to not write any prefixes (currently it's only relevant to csv)

**Comment by korg1000** [comment]
Today there is anyway to save two or more chats same time? I tried to put -c @channel1 -c @channel2 , but dont work. It would be nice to do, thanks.

**Comment by Kosat** [comment]
@fxcp 
Committed the code. 49b3aaea872ca34ab5bb02a76c897971736537fb
The explanation is here https://github.com/Kosat/telegram-messages-dump#increamentalcontinuous-mode

**Comment by Kosat** [comment]
@korg1000  telegram-messages-dump doesn't merge dumps from different channels into one file.
I'm not planning to add this functionality, because there're plenty ways to easily merge files into one on any OS.

**Comment by korg1000** [comment]
Ok thanks. If you just compile to windows the new version, i'll be happy, thanksEm 29 de abr de 2018 10:48 AM, Kostya <notifications@github.com> escreveu:@korg1000  telegram-messages-dump doesn't merge dumps from different channels into one file.
I'm not planning to add this functionality, because there're plenty ways to easily merge files into one on any OS.

**Comment by Kosat** [comment]
@korg1000  
Try this one. I didn't have much time to test it, so, please, let me know if there're problems.
https://github.com/Kosat/telegram-messages-dump/releases/tag/v0.3.0

**Comment by korg1000** [comment]
Hi, i tested it, and now say an error:
INFO: Starting to wait for items, from the network
WARNING: Request invoked too often, wait 23s

I'm using same command line from old release. And by the way, the old release works. But i need the new release, with private name title function. Thanks

**Comment by Kosat** [comment]
@korg1000 what was the command? Please, post it here excluding the phone number. And tell me your OS.

**Comment by korg1000** [comment]
-p Phonenumber -c @channelEm 1 de mai de 2018 2:03 PM, Kostya <notifications@github.com> escreveu:@korg1000 what was the command (without your phone number) ?

**Comment by Kosat** [comment]
`-p Phonenumber -c @channel`
@korg1000 what was the channel name? I've tried v0.3 on different chats and everything is working.
Another thing that comes to mind is that the old session file may cause problems, so you should try to delete it.

**Comment by korg1000** [comment]
@mastersignals is an example. Every other channels, same error. Deleting old session, same error. I'm using the windows release ok?

**Comment by Kosat** [comment]
@korg1000 Please, run it in verbose mode using `-v` parameter and copy-paste the output here.

**Comment by korg1000** [comment]
![capturar](https://user-images.githubusercontent.com/18563504/39625789-79e5b1d6-4f75-11e8-8903-852898b08af6.PNG)
The verpose output is almost same message like the image attached. If you need better output, please tell me. Thanks.

**Comment by Kosat** [comment]
@korg1000 
It's totally unclear why it's happening on your machine.
I forwarded your problem to the author of the Python Telegram API wrapper that this tool relies on and he also seem to be [clueless](https://github.com/LonamiWebs/Telethon/issues/794#event-1610647520). 

In a meanwhile I've updated the version of Telethon and made some other minor changes and published a new build. [v0.3.1](https://github.com/Kosat/telegram-messages-dump/releases/tag/v0.3.1)
You can try it, but most probably it wont help your problem (at least when it comes to private chats).

BTW: 
1. What version of Windows and Python do you use on that machine?
2. And how many channels and all sorts of dialogues do you have in Telegram (approximately) ?

**Comment by korg1000** [comment]
Yes, now it works. If i use the @mastersignals, ok, it work again. But if i dont have the @channel, how i will read the chats from channel? -c "the title of private channel i'm subscribed"? Can i use the channel id? Ex.
https://web.telegram.org/#/im?p=c1338903118_14484119872565569755

**Comment by Kosat** [comment]
@korg1000 Added a new option `--channelid` to bypass the name resolution. It is supposed to be used __instead of__ the `--chat` option.
[Check up the Note2](https://github.com/Kosat/telegram-messages-dump#usage) and the new build [0.3.2](https://github.com/Kosat/telegram-messages-dump/releases/tag/v0.3.2)

**Comment by Kosat** [comment]
Huh, I looked all over the Teleram API and couldn't find a good way of making this differently, in a better way.
The Telethon's author also suggested [nothing](https://github.com/LonamiWebs/Telethon/issues/797#event-1611836945)

PS: I was deleting my comment in this thread and by mistake deleted yours (korg1000) too. Pardon me. This was unintentional.

**Comment by korg1000** [comment]
Dont worry, no problem at all. I followed the 0.3.2 link from the new windows release, but it dont exist. Its broken.Em 6 de mai de 2018 5:14 PM, Kostya <notifications@github.com> escreveu:Huh, I looked all over the Teleram API and couldn't find a good way of making this differently, in a better way.
The Telethon's author also suggested nothing
PS: I was deleting my comment in this thread and by mistake deleted yours (korg1000) too. Pardon me. This was unintentional.

**Comment by Kosat** [comment]
@korg1000 
>>Dont worry, no problem at all. I followed the 0.3.2 link from the new windows release, but it dont exist. Its broken.Em 6 de mai de 

Yeah, it doesn't exist because I had to rollback the commit and delete the build. I found out that there was a critical problem with that solution. So far, I still have no solution to your problem.

**Comment by Kosat** [comment]
@korg1000 
Hi, I've re-buit and re-uploaded the [v0.3.1](https://github.com/Kosat/telegram-messages-dump/releases/tag/v0.3.1)
Please, try to dump your private channel like you did before 
`telegram-messages-dump.exe ... --chat="private chat title"`
If it still doesn't work, try this new way

> Note2: For private channels you can also pass an invitation link as chat name. E.g. --chat="https://t.me/joinchat/XXXXXYYYYZZZZZ". IMPORTANT: It only works when you (the logged-in user) has already joined the private chat that the invitation link corresponds to.

The invitation link has to start from `https://t.me/joinchat/` !

**Comment by korg1000** [comment]
Well, with private chat title dont work, gives request invokeed too often. Then i try with the invite link, and gives me invite hash is invalid. But not all my private channel has invite link. Some of them put me in directly. And with id from channel, there is any way to do?

**Comment by Kosat** [comment]
>But not all my private channel has invite link. 

When you use the Desktop client you can't get the invitation link?
![image](https://user-images.githubusercontent.com/153023/39719223-3ebe4f5e-5241-11e8-8684-6370e167ffdc.png)

>And with id from channel, there is any way to do?

No, knowing the ChannelId isn't enough. :(

**Comment by korg1000** [comment]
Ok, no problem. Thanks for your effort.Em 7 de mai de 2018 3:56 PM, Kostya <notifications@github.com> escreveu:
But not all my private channel has invite link.
When you use the Desktop client you can't get the invitation link?



And with id from channel, there is any way to do?
No, knowing the ChannelId isn't enough. :(

**Comment by korg1000** [comment]
No, i cant get the invite link because the private channel is not mine. I'm just putted in, directly, whithout link invitation. Did you think with the -chat="name of the private channel" option, will not work, there is no hope? Because i think it will be the solution of my problem :) . I dont need the continuum, nothing of it. I'm just need to save the content of the private channel, every time i call the telegram_dump.exe, just it. Thanks
