### ISSUE TITLE
More robust error handling

### ISSUE THREAD

**Issue by fxcp** [Kosat/telegram-messages-dump#11]
* Clean temporary files in case of error
```
~> ls /tmp
*snip*
 tmp05du3ixs
 tmp0n247tf3
 tmp0vvu04yo
 tmp1q2n_ihv
 tmp3kj7o7gi
 tmp62emsoxb
 tmp6wj05ie0
 tmp7v_8i3p7
 tmpa1rkn8yq
 tmpa48ct2z3
 tmpbz8527p6
 tmpe8u4ckfp
 tmpg76f675h
 tmph2d3ne26
 tmpi5jva1i6
 tmpj8ccctns
 tmpj8reg5p8
 tmpjo436qv3
 tmpkdep2ist
 tmpl4gpptbd
 tmplu0xi49a
 tmpm73f50ww
 tmpojemi7nr
 tmppgw7_h38
 tmpq2_x5se2
 tmpqxhyt0ui
 tmp_uqgjofc
 tmpusg7_s9m
 tmpux0hldrk
 tmpuzuebz81
 tmp_wgk9u3o
 tmpyrd71m5j
 tmpzmjqufsj
 tmpznp5vvhf
```

* Retry X times in case of RPC error (sometimes I get "Telegram is having internal issues now, retry later"). Would be useful when dumping full history of big chats.

* Provide more user-friendly error message instead of scary stacktrace.

--
Thanks for such a good dumper, finally we can replace broken and abandoned [telegram-history-dump](https://github.com/tvdstaaij/telegram-history-dump) ;)

**Comment by Kosat** [comment]
In 72b97a5
> Retry X times in case of RPC error

Telethon is already making 5 attempts to reconnect. I don't see how I can improve it here. 

> Provide more user-friendly error message instead of scary stacktrace.
+ Verbose mode
+ Strategy changed from all-or-nothing to partial-success.
Now when dumper retrieves only some of the messages it will still generate an output file rather than just crash with exception. Problem here is how to make it MORE clear to a user that what he got in output file is not everything he/she wanted to get.
+ More exception handling.  No leftover temp files.

**Comment by ghost** [comment]
I get high.

**Comment by ghost** [comment]
This will work great for generating chatterbot corpus of conversations. It would be extra legit if there was actually a corpus export mode that could integrate with chatterbot since chatterbot has a serious lack of corpus dictionaries.

**Comment by fxcp** [comment]
> It would be extra legit if there was actually a corpus export mode that could integrate with chatterbot since chatterbot has a serious lack of corpus dictionaries

@MoonGem, It's not very hard to implement "exporter" for chatterbot format.


>it will still generate an output file rather than just crash with exception.

Not every error is critical, one good exception is `telethon.errors.rpc_base_errors.ServerError`.

**Comment by fxcp** [comment]
Looks like nobody cares about `ServerError`. Closing... 
P.S. If someone actually does - reopen this issue.
