### ISSUE TITLE
Mixed message_ids

### ISSUE THREAD

**Issue by wowkin2** [Kosat/telegram-messages-dump#13]
I want to retrieve history from channel where I have 22K of messages.
When I dump with this tool message ids are mixed sometimes.
Tried to get last 2200 messages - got them in following order:
```
200 items: #18854-19087
1000 items: #20243-21342
1000 items: #19088-20242
```
3500 messages:
```
500: #17269-17925
1000: #20243-21342
1000: #19088-20242
1000: #17928-19087
```

**Comment by wowkin2** [comment]
Can be easy fixed, by replacing `.popleft()` to `.pop()` in `telegram_dumper.TelegramDumper()::_merge_temp_files_into_final`

Should I create Pull Request or you can handle that?

**Comment by fxcp** [comment]
Am I blind?
```
$ rg "popleft"
$ rg "pop"
telegram_messages_dump/telegram_dumper.py
195:                            print(buffer.pop(), file=tf)
216:                print(buffer.pop(), file=resulting_file)
```

By the way, looks like Kosat is a busy person and can't respond quickly to all issues. Create PR if you can.

**Comment by Kosat** [comment]
Guys, sorry for the delay.

The fix of "replacing .popleft() to .pop()" looks right, so far. I've included it into the latest commit. 2beb763951dfcb37aa36f8c1dffc40a9560c833e
I'll do more testing to check it in various scenarios, though.

**Comment by wowkin2** [comment]
@Kosat, thanks for quick update

**Comment by Kosat** [comment]
Please, feel free to open a new issue if this or other problem occurs.
