### ISSUE TITLE
I get an error when running telegram-messages-dump

### ISSUE THREAD

**Issue by mpgigat** [Kosat/telegram-messages-dump#14]
I'm trying to run telegram-messages-dump on windows 10. I usually clone and install python. But I get the error of the image when running the telegram-messages-dump command.

Any ideas of what I may be doing wrong, or is it an issue with windows?

![image](https://user-images.githubusercontent.com/34031062/41353212-32c656e4-6ee1-11e8-8bae-54eded747051.png)

**Comment by Kosat** [comment]
Hi @mpgigat,

The error on the screenshot happens because you are running the tool on Python 2.7.
Instead, you should run `telegram-messages-dump`  on the latest stable version of **Python 3.x**.

**Comment by mpgigat** [comment]
thanks
