### ISSUE TITLE
ERROR:Uncaught exception occured. 'Chat' object has no attribute 'username'

### ISSUE THREAD

**Issue by Teoretic6** [Kosat/telegram-messages-dump#17]
Hello!

I get this strange error and can't figure out what is causing it:
_"ERROR:Uncaught exception occured. 'Chat' object has no attribute 'username'"_

I successfully got and entered verification code from Telegram.
I'm using multi-word name of the chat.

Python 3.6.5
Linux Mint 18.3 (if it matters)

![screenshot from 2018-07-21 22-30-56](https://user-images.githubusercontent.com/9078134/43039458-5416a98e-8d36-11e8-9434-8b9c9658ad0c.png)

Any ideas on what is causing it?

**Comment by Teoretic6** [comment]
**Found an issue in code after debugging**
![screenshot from 2018-07-21 23-37-14](https://user-images.githubusercontent.com/9078134/43039936-6eab6d70-8d40-11e8-9946-16c58da4bda5.png)

telegram_dumper.py, line 192

**The issue is that group chat objects has no such field as "username", only dialogs with users have them.**

Here's the example of the object of dialog with user:
![screenshot from 2018-07-22 00-29-16](https://user-images.githubusercontent.com/9078134/43040211-b66a0076-8d46-11e8-8f58-47e84386f267.png)

It contains "username" field.

Will PR on this soon :)

**Comment by Kosat** [comment]
Thank you. I've accepted your PR and fixed the Travis MacOS build. 
Cheers!
