### ISSUE TITLE
-l 0 takes 0 messages, not all messages from the group

### ISSUE THREAD

**Issue by set92** [Kosat/telegram-messages-dump#20]
I tried running "telegram-messages-dump --chat="----" -p +3----- -e csv -l 0" and it says me

> Dumping 0 messages into "telegram_--aDeZaBA.log" file ...
> Merging results into an output file.
> INFO:Writing a new metadata file.
> 0 messages were successfully written in the resulting file. Done!

**Comment by Kosat** [comment]
Hi,
This problem is supposed to be fixed in [v0.3.5](https://github.com/Kosat/telegram-messages-dump/releases/tag/v0.3.5)
