### ISSUE TITLE
Stops with a limit=0

### ISSUE THREAD

**Issue by MrGreenTea** [Kosat/telegram-messages-dump#21]
I tried to export all messages of a chat I have. It stopped working after this log:

```
Processing messages with ids 44150-42271 ...
Processing messages with ids 42266-41564 ...
Processing messages with ids 41545-41525 ...
```

This also looks like a way smaller range of ids than all previous logs.

Also, when I `Ctrl+C` now, it doesn't write anything to the file, even though the message says it does. The file is created, but completely empty with a size of 0.

**Comment by Kosat** [comment]
Hi @MrGreenTea,

Thanks for reporting the problem.

>_This also looks like a way smaller range of ids than all previous logs._

Yes, actually in your log all the ranges are wrong for some reason. The ranges are supposed to be of 100 messages, except for the very last one.

Can you tell me what channel was you dumping? What other parameters you had used?

**Comment by MrGreenTea** [comment]
I was dumping a private chat. 
I started the dump with these parameters:
`telegram-messages-dump --phone="XXXXXXXX" --chat="FRIEND_NAME" --limit=0 --exp=csv --out=FRIEND_NAME_full.csv`

**Comment by Kosat** [comment]
@MrGreenTea,

Does it work if you specify some other specific limit, not 0?
Do you really have around 40000 messages in that private chat? 
Unfortunately, I never tested the tool on a long private chats. I only use Telegram for chatting in public groups. :)
