### ISSUE TITLE
Script stops while exporting a chat with 400 000+ messages

### ISSUE THREAD

**Issue by e-magon** [Kosat/telegram-messages-dump#22]
Hi, I'm trying to export a chat with more than 400'000 messages, but the script stops after a while saying:
`Processing messages with ids 1084908-1084785 ...`
And it doesn't go on.

What can I do?

Thanks

**Comment by wowkin2** [comment]
Is it public? Can you share it to reproduce?

**Comment by e-magon** [comment]
No, unfortunately it's a private chat
