### ISSUE TITLE
Uncaught exception occured

### ISSUE THREAD

**Issue by olivier91000** [Kosat/telegram-messages-dump#24]
Hello, 

Could please correct this error :

ERROR:Uncaught exception occured. Cannot cast NoneType to any kind of InputPeer.
0 messages were successfully written in the resulting file. Done!

This is a private channel, I tried 3 differents and it throw the same error. Created a test channel with dummy messages and also got the same error. 

Best regards

**Comment by olivier91000** [comment]
"telegram-messages-dump -c @firendlyname -p +xxxxxxxxxx"

Als setting different limit did not solve the issue.

Processing messages with ids 17-1 ...
ERROR:Uncaught exception occured. Cannot cast NoneType to any kind of InputPeer.
0 messages were successfully written in the resulting file. Done!
I tried a public channel with the same issue "@football" for instance.

**Comment by Kosat** [comment]
Fixed.
