### ISSUE TITLE
Socket error: timed out

### ISSUE THREAD

**Issue by wowkin2** [Kosat/telegram-messages-dump#25]
I had an issue with timeout error.
If you'll have something similar - just need to increase connection timeout from 10 (default) to 40 in `telegram_dumper.py`.
Solution from here https://github.com/LonamiWebs/Telethon/issues/801#issuecomment-388623832

If anybody else will also have the same issue, comment here. Maybe we'll need to create pull-request for that.

**Comment by Kosat** [comment]
Fixed. Increased timeout to 40. Thanks.
