### ISSUE TITLE
Latest osx binary is not useable

### ISSUE THREAD

**Issue by reorx** [Kosat/telegram-messages-dump#26]
Running the osx binary in latest release (0.3.5) will raise error as below:

```
$ ./telegram-messages-dump
Fatal Python error: initfsencoding: unable to load the file system codec
zipimport.ZipImportError: can't find module 'encodings'

Current thread 0x00007fff97c8b380 (most recent call first):
[1]    66361 abort      ./telegram-messages-dump
```

This seems to be the problem of pyinstaller, which is said not compatible with Python 3.7 in this issue: https://github.com/pyenv/pyenv/issues/1095

I tried to build the binary with 3.6.7 on my mac, and the result works properly. Maybe you should restrict the python version to 3.6.X in the travis build script?

**Comment by Kosat** [comment]
Sorry. Unfortunately, I can't test nor fix MacOS binaries right now, so I removed them.
