### ISSUE TITLE
Export usernames

### ISSUE THREAD

**Issue by crayxt** [Kosat/telegram-messages-dump#27]
Hi,
Is it possible to export displayed usernames (together with telegram id's)?
Thanks,

**Comment by Kosat** [comment]
Hi @crayxt ,

It's quite easy to do it by modifying a couple of lines of an exporter class (text, jsonl or csv). You can get user id from `msg.sender_id`.

For example for the text exporter it'd be something like
``` Python
 msg_dump_str = '[{}-{:02d}-{:02d} {:02d}:{:02d}] ID={} {}{} {}: {}'.format(
     msg.date.year, msg.date.month, msg.date.day,
     msg.date.hour, msg.date.minute, msg.id, "RE_ID=%s " % re_id if re_id else "",
     name, getattr(msg, "sender_id", None) ,self._py_encode_basestring(content))
```

**Comment by crayxt** [comment]
Hi @Kosat thanks for your reply and example code, will try to do that!
