### ISSUE TITLE
ERROR:Uncaught exception occurred. Cannot cast NoneType to any kind of InputPeer.

### ISSUE THREAD

**Issue by mkellerman** [Kosat/telegram-messages-dump#29]
Trying to dump a public channel "Durov's Channel"

![image](https://user-images.githubusercontent.com/9411143/50354331-2c799e80-0519-11e9-944b-13fcc2699878.png)

**Comment by Ealireza** [comment]
same error here

**Comment by Kosat** [comment]
Fixed.
