### ISSUE TITLE
Machine-readable output (JSONL)

### ISSUE THREAD

**Issue by ghost** [Kosat/telegram-messages-dump#3]
I want to use your script to collect message history and then process it using another script to form... some kind of statistics.

It would be very nice to have  `--json` argument with output format like https://github.com/tvdstaaij/telegram-history-dump#formatters.

**Comment by ghost** [comment]
Following information about messages can be useful:
- [ ] __Message ID__
- [ ] Sender ID
- [ ] __Sender is bot?__
- [ ] __Is this message forwarded from somewhere?__
- [ ] Timestamp
- [ ] __What kind of media contained in this message, if any.__

**Comment by Kosat** [comment]
Good point. Added json exporter in v0.2.0. See `--exp` setting.
