### ISSUE TITLE
Save history of groups without public link

### ISSUE THREAD

**Issue by fxcp** [Kosat/telegram-messages-dump#6]
It would be nice to be able to save messages from groups without public link (private groups), something like this:
```
~> python3 -m telegram_messages_dump -c "group name here" -p ... -l 0
```
but:
```
__main__.py: error: Chat name must start with "@"
```

**Comment by korg1000** [comment]
please, compile this alteration to windows too. Because i'm trying to get my private channels dumps and can't because i dont get the @unique_name from private channel, and the .exe get me an error: must start with @
