### ISSUE TITLE
Consider removing UTF-8 Byte Order Mark

### ISSUE THREAD

**Issue by fxcp** [Kosat/telegram-messages-dump#9]
>The Unicode Standard permits the BOM in UTF-8, but does not require or recommend its use. **Byte order has no meaning in UTF-8, so its only use in UTF-8 is to signal at the start that the text stream is encoded in UTF-8,** or that it was converted from another stream that contained an optional BOM. The standard also does not recommend removing a BOM when it is there, so that round-tripping between encodings does not lose information, and so that code that relies on it continues to work. **The IETF recommends that if a protocol either (a) always uses UTF-8, or (b) has some other way to indicate what encoding is being used, then it "SHOULD forbid use of U+FEFF as a signature."**

-- https://en.wikipedia.org/wiki/Byte_order_mark

Additionally BOM can cause issues in Unicode-unaware programs (and even aware ones! `json.loads` fails if BOM is present).

**Comment by Kosat** [comment]
Well, I can add another option like `--no-bom`. 
Its a low-priority issue, though.

**Comment by fxcp** [comment]
Considering all issues created by presence of BOM I would make "no bom" the default with `--bom` option if you really need it sometimes.

**Comment by Kosat** [comment]
Ok, point is taken. Now BOM is not included by default. Yet, it can be included on demand using `--addbom` option.
